import { ThemedText } from "@/components/ThemedText";
import Spacer from "@/components/Spacer";
import React from "react";
import { Pressable, ScrollView, View } from "react-native";

interface ListItemProps {
  children: React.ReactNode;
}

const ListItem: React.FC<ListItemProps> = ({ children }) => {
  return (
    <View className="flex-row">
      <View className="w-6">
        <ThemedText className="text-center font-bold">•</ThemedText>
      </View>
      <View className="flex-1">
        <ThemedText>{children}</ThemedText>
      </View>
    </View>
  );
};

interface UnorderedListProps {
  children: React.ReactNode;
}

const UnorderedList: React.FC<UnorderedListProps> = ({ children }) => {
  return <View>{children}</View>;
};

interface PrivacyPolicyProps {
  callback: () => void;
}

export const PrivacyPolicy: React.FC<PrivacyPolicyProps> = ({ callback }) => {
  const definitions = [
    {
      term: "Account",
      definition:
        "means a unique account created for You to access our Service or parts of our Service.",
    },
    {
      term: "Affiliate",
      definition:
        'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
    },
    {
      term: "Application",
      definition:
        "refers to MetaVault, the software program provided by the Company.",
    },
    {
      term: "Company",
      definition:
        '(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to MetaVault.',
    },
    {
      term: "Cookies",
      definition:
        "are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your Browse history on that website among its many uses.",
    },
    { term: "Country", definition: "refers to: Indonesia" },
    {
      term: "Device",
      definition:
        "means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
    },
    {
      term: "Personal Data",
      definition:
        "is any information that relates to an identified or identifiable individual.",
    },
    {
      term: "Service",
      definition: "refers to the Application or the Website or both.",
    },
    {
      term: "Service Provider",
      definition:
        "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
    },
    {
      term: "Usage Data",
      definition:
        "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
    },
    {
      term: "Website",
      definition:
        "refers to MetaVault, accessible from https://password-manager.expo.app",
    },
    {
      term: "You",
      definition:
        "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
    },
  ];

  return (
    <View className="absolute bg-white w-full z-20 bottom-0 rounded-t-lg h-3/4">
      <View className="rounded-t-lg bg-[#EBEBEB] flex flex-row justify-between py-3 px-6 items-center">
        <View className="flex-1">
          <Pressable onPress={callback}>
            <ThemedText fontSize={14} className="text-[#0099FF]">
              Close
            </ThemedText>
          </Pressable>
        </View>
        <View className="flex-1 items-center">
          <ThemedText fontSize={14} fontWeight={700}>
            Privacy policy
          </ThemedText>
        </View>
        <View className="flex-1" />
      </View>

      <ScrollView contentContainerClassName="p-6">
        <ThemedText fontWeight={700} fontSize={18} className="text-black">
          Privacy Policy
        </ThemedText>
        <Spacer size={8} />
        <ThemedText fontSize={12} className="text-gray-600">
          Last updated: July 28, 2025
        </ThemedText>

        <Spacer size={20} />

        <ThemedText className="text-gray-800">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </ThemedText>
        
        <Spacer size={12} />
        
        <ThemedText className="text-gray-800">
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </ThemedText>

        <Spacer size={24} />

        <ThemedText fontWeight={700} fontSize={16} className="text-black">
          Interpretation
        </ThemedText>
        <Spacer size={8} />
        <ThemedText className="text-gray-800">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </ThemedText>

        <Spacer size={24} />

        <ThemedText fontWeight={700} fontSize={16} className="text-black">
          Definitions
        </ThemedText>
        <Spacer size={8} />
        <ThemedText className="text-gray-800">
          For the purposes of this Privacy Policy:
        </ThemedText>
        <Spacer size={12} />
        <UnorderedList>
          {definitions.map((item, index) => (
            <ListItem key={index}>
              <ThemedText fontWeight={700} className="text-black">
                {item.term}
              </ThemedText>{" "}
              <ThemedText className="text-gray-800">{item.definition}</ThemedText>
            </ListItem>
          ))}
        </UnorderedList>

        <Spacer size={24} />

        <ThemedText fontWeight={700} fontSize={16} className="text-black">
          Personal Data Collected
        </ThemedText>
        <Spacer size={8} />
        <ThemedText className="text-gray-800">
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </ThemedText>
        <Spacer size={12} />
        <UnorderedList>
          <ListItem>
            <ThemedText className="text-gray-800">Email address</ThemedText>
          </ListItem>
          <ListItem>
            <ThemedText className="text-gray-800">First name and last name</ThemedText>
          </ListItem>
          <ListItem>
            <ThemedText className="text-gray-800">Usage Data</ThemedText>
          </ListItem>
        </UnorderedList>

        <Spacer size={24} />

        <ThemedText fontWeight={700} fontSize={16} className="text-black">
          Usage Data
        </ThemedText>
        <Spacer size={8} />
        <ThemedText className="text-gray-800">
          Usage Data is collected automatically when using the Service. Usage
          Data may include information such as Your Device&apos;s Internet Protocol
          address (e.g. IP address), browser type, browser version, the pages of
          our Service that You visit, the time and date of Your visit, the time
          spent on those pages, unique device identifiers and other diagnostic
          data.
        </ThemedText>

        <Spacer size={12} />

        <ThemedText className="text-gray-800">
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including, but not limited
          to, the type of mobile device You use, Your mobile device unique ID,
          the IP address of Your mobile device, Your mobile operating system,
          the type of mobile Internet browser You use, unique device identifiers
          and other diagnostic data.
        </ThemedText>

        <Spacer size={24} />

        <ThemedText fontWeight={700} fontSize={16} className="text-black">
          Information Collected while Using the Application
        </ThemedText>
        <Spacer size={8} />
        <ThemedText className="text-gray-800">
          While using Our Application, in order to provide features of Our
          Application, We may collect, with Your prior permission:
        </ThemedText>
        <Spacer size={12} />
        <UnorderedList>
          <ListItem>
            <ThemedText className="text-gray-800">Information regarding your location</ThemedText>
          </ListItem>
        </UnorderedList>
        <Spacer size={12} />
        <ThemedText className="text-gray-800">
          We use this information to provide features of Our Service, to improve
          and customize Our Service. The information may be uploaded to the
          Company&apos;s servers and/or a Service Provider&apos;s server or it may be
          simply stored on Your device. You can enable or disable access to this
          information at any time, through Your Device settings.
        </ThemedText>

        <Spacer size={24} />

        <ThemedText fontWeight={700} fontSize={16} className="text-black">
          Contact Us
        </ThemedText>
        <Spacer size={8} />
        <ThemedText className="text-gray-800">
          If you have any questions about this Privacy Policy, You can contact
          us:
        </ThemedText>
        <Spacer size={12} />
        <UnorderedList>
          <ListItem>
            <ThemedText className="text-gray-800">By email: szarifin20041@gmail.com</ThemedText>
          </ListItem>
        </UnorderedList>
        <Spacer size={24} />
      </ScrollView>
    </View>
  );
};
